# -*- coding: utf-8 -*-
"""finalPrepro-9.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Xey6AQKgZJumI9BDUa-5NLPTUy7ucP2F
"""

# Install PyEI from PyPI.
!pip install pyei --quiet

import numpy as np
import pandas as pd
import warnings
warnings.filterwarnings('ignore')

from pyei.r_by_c import RowByColumnEI

print('PyEI imported successfully.')

from google.colab import files

print('Please upload: or_combined_data.csv AND sc_combined_data.csv')
uploaded = files.upload()
print('Uploaded files:', list(uploaded.keys()))

def load_and_validate(filename):
    """
    Loads a state CSV, validates required columns, and filters out
    precincts with zero total votes or zero total population.
    Returns a clean DataFrame.
    """
    df = pd.read_csv(filename)

    required_cols = [
    'precinct_id', 'total', 'white', 'black', 'asian', 'hispanic',
    'democratic_votes', 'republican_votes', 'total_votes'
    ]
    missing = [c for c in required_cols if c not in df.columns]
    if missing:
        raise ValueError(f'Missing columns in {filename}: {missing}')

    original_len = len(df)

    # Drop rows with no voters or no population — EI cannot handle these
    df = df[(df['total_votes'] > 0) & (df['total'] > 0)].copy()
    dropped = original_len - len(df)
    if dropped > 0:
        print(f'  Dropped {dropped} rows with zero total_votes or total population.')

    # Reset index for clean iteration
    df = df.reset_index(drop=True)

    print(f'  Loaded {len(df)} precincts from {filename}.')
    return df


print('Loading Oregon...')
oregon_df = load_and_validate('or_combined_data.csv')

print('Loading South Carolina...')
sc_df = load_and_validate('sc_combined_data.csv')

print('\nOregon sample:')
display(oregon_df.head(3))

print('\nSouth Carolina sample:')
display(sc_df.head(3))

# Cell 5
from pyei.two_by_two import TwoByTwoEI

RACIAL_GROUPS = ['white', 'black', 'asian', 'hispanic']

# ─────────────────────────────────────────────────────────────────────────────
# STEP A: Build 2x2 EI inputs for one racial group
# ─────────────────────────────────────────────────────────────────────────────

def build_2x2_inputs(df, group_name):
    """
    Builds inputs for a single 2x2 EI run for one racial group.

    group_fraction : fraction of precinct population belonging to this group
    vote_fraction  : fraction of total votes cast that were Democratic
                     (we use Dem vs non-Dem as the two outcomes)
    precinct_pops  : total_votes as integers (multinomial denominator)
    """
    total_pop = df['total'].values.astype(float)
    group_pop = df[group_name].values.astype(float)

    # Group fraction of total population
    total_pop_safe = np.where(total_pop == 0, 1.0, total_pop)
    group_fraction = np.clip(group_pop / total_pop_safe, 1e-6, 1.0 - 1e-6)

    # Democratic vote fraction of total votes cast
    tot_votes = df['total_votes'].values.astype(int)
    dem_votes = df['democratic_votes'].values.astype(int)
    tot_safe  = np.where(tot_votes == 0, 1, tot_votes).astype(float)
    dem_fraction = np.clip(dem_votes / tot_safe, 1e-6, 1.0 - 1e-6)

    precinct_pops = tot_votes.copy()

    return group_fraction, dem_fraction, precinct_pops


# ─────────────────────────────────────────────────────────────────────────────
# STEP B: Run one 2x2 EI model for one racial group
# ─────────────────────────────────────────────────────────────────────────────

def run_2x2_ei(group_fraction, dem_fraction, precinct_pops,
               group_name, n_samples=1000, n_tune=500):
    """
    Runs PyEI TwoByTwoEI with ei_bivariate_normal model.
    This model is the most numerically stable option and does not
    require integer count consistency between precinct_pops and vote fractions.
    """
    print(f'    Running 2x2 EI for group: {group_name} ...')

    ei = TwoByTwoEI(model_name='truncated_normal')

    ei.fit(
        group_fraction=group_fraction,
        votes_fraction=dem_fraction,
        precinct_pops=precinct_pops,
        demographic_group_name=group_name,
        candidate_name='democratic',
        draws=n_samples,
        tune=n_tune,
        target_accept=0.99,
    )

    return ei


# ─────────────────────────────────────────────────────────────────────────────
# STEP C: Extract per-precinct estimates from a 2x2 EI result
# ─────────────────────────────────────────────────────────────────────────────

def extract_2x2_precinct_estimates(ei, group_fraction, dem_fraction, precinct_pops):
    """
    TwoByTwoEI sampled_voting_prefs has shape (2, n_samples):
      row 0 = samples of fraction of GROUP voting Democratic (b_1)
      row 1 = samples of fraction of NON-GROUP voting Democratic (b_2)

    For per-precinct estimates, we use the statewide posterior means (b1, b2)
    combined with the precinct-level accounting identity:

      T_i = X_i * b1_i + (1 - X_i) * b2_i

    where T_i = observed dem_fraction in precinct i
          X_i = group_fraction in precinct i

    We use the statewide b2 posterior mean as a baseline and solve for
    the implied per-precinct b1:

      b1_i = (T_i - (1 - X_i) * b2) / X_i

    This gives precinct-specific estimates that are consistent with both
    the observed vote totals and the statewide EI posterior.
    For precincts where X_i is very small, we fall back to the statewide b1 mean.
    """
    samples = np.array(ei.sampled_voting_prefs)  # (2, n_samples)

    b1_mean = float(samples[0, :].mean())  # statewide: group -> dem
    b2_mean = float(samples[1, :].mean())  # statewide: non-group -> dem

    X = group_fraction   # (n_precincts,)
    T = dem_fraction     # (n_precincts,)

    # Solve per-precinct b1 from the accounting identity
    # b1_i = (T_i - (1 - X_i) * b2) / X_i
    with np.errstate(divide='ignore', invalid='ignore'):
        b1_precinct = (T - (1.0 - X) * b2_mean) / X

    # Where group fraction is too small (<2%), fall back to statewide mean
    b1_precinct = np.where(X < 0.02, b1_mean, b1_precinct)

    # Clip to valid probability range
    b1_precinct = np.clip(b1_precinct, 0.0, 1.0)

    return b1_precinct, b2_mean, b1_mean, samples


# ─────────────────────────────────────────────────────────────────────────────
# STEP D: Compute statewide estimates and confidence score from 2x2 EI
# ─────────────────────────────────────────────────────────────────────────────

def compute_2x2_statewide(samples, precinct_pops, group_fraction):
    """
    Computes statewide EI estimates following the Becker/VRA-Ensembles paper.

    Confidence is computed using the logistic transformation from Footnote 15:
        p   = frequency across MCMC draws that Dem votes > Rep votes for this group
        C(p) = 1 / (1 + exp(18 - 26*p))

    This transformation ensures:
      - p = 0.50 (toss-up)  → C(p) ≈ 0.00  (almost no weight)
      - p = 0.85            → C(p) ≈ 1.00  (nearly full confidence)
    """
    b1_samples = samples[0, :]  # (n_samples,) — fraction of group voting Dem per draw
    b2_samples = samples[1, :]  # (n_samples,) — fraction of non-group voting Dem per draw

    total_group_pop = float((group_fraction * precinct_pops).sum())

    # Estimated statewide Dem and Rep votes from this group per draw
    statewide_dem = b1_samples * total_group_pop  # (n_samples,)
    statewide_rep = (1.0 - b1_samples) * total_group_pop  # (n_samples,)

    # p = frequency with which Dem is the preferred candidate across draws
    p = float((statewide_dem > statewide_rep).mean())

    # Party of choice = whichever party won more often
    if p >= 0.5:
        party_of_choice = 'democratic'
    else:
        party_of_choice = 'republican'
        p = 1.0 - p  # flip p to always refer to the party of choice

    # C(p) logistic transformation from Footnote 15 of VRA-Ensembles paper
    confidence = 1.0 / (1.0 + np.exp(18.0 - 26.0 * p))

    mean_dem_votes    = float(statewide_dem.mean())
    mean_rep_votes    = float(statewide_rep.mean())
    mean_dem_fraction = float(b1_samples.mean())
    mean_rep_fraction = float(1.0 - b1_samples.mean())

    return party_of_choice, confidence, mean_dem_votes, mean_rep_votes, mean_dem_fraction, mean_rep_fraction


print('All helper functions defined.')

# Cell 6

def run_prepro9_for_state(df, state_name,
                           precinct_output_filename,
                           statewide_output_filename,
                           samples_output_filename,
                           n_samples=1000, n_tune=500):
    print(f'\n{"="*60}')
    print(f'  Prepro-9 EI Analysis: {state_name}')
    print(f'{"="*60}')
    print(f'  Precincts: {len(df)}')

    precinct_out = pd.DataFrame()
    precinct_out['precinct_id'] = df['precinct_id'].values
    precinct_out['state']       = state_name
    precinct_out['total_votes'] = df['total_votes'].values

    statewide_rows = []
    samples_rows = []

    for group_name in RACIAL_GROUPS:
        print(f'\n  ── Group: {group_name} ──')

        # A: Build inputs
        group_fraction, dem_fraction, precinct_pops = build_2x2_inputs(df, group_name)

        # B: Run EI
        ei = run_2x2_ei(group_fraction, dem_fraction, precinct_pops,
                         group_name, n_samples=n_samples, n_tune=n_tune)

        # C: Per-precinct estimates
        b1_precinct, b2_mean, b1_mean, samples = extract_2x2_precinct_estimates(
            ei, group_fraction, dem_fraction, precinct_pops)

        precinct_out[f'ei_{group_name}_dem_vote_fraction'] = b1_precinct.round(6)
        precinct_out[f'ei_{group_name}_rep_vote_fraction'] = (1.0 - b1_precinct).round(6)
        precinct_out[f'ei_{group_name}_party_of_choice']   = np.where(
            b1_precinct >= 0.5, 'democratic', 'republican')
        precinct_out[f'ei_{group_name}_precinct_confidence'] = np.where(
            b1_precinct >= 0.5, b1_precinct, 1.0 - b1_precinct).round(4)

        # Accumulate MCMC posterior samples for KDE generation
        # samples[0] = b1 draws (focal group → DEM), samples[1] = b2 draws (non-focal → DEM)
        samples_rows.append({
            'state':        state_name,
            'racial_group': group_name,
            'b1_samples':   ','.join(f'{v:.6f}' for v in samples[0, :].tolist()),
            'b2_samples':   ','.join(f'{v:.6f}' for v in samples[1, :].tolist()),
        })

        # D: Statewide
        poc, conf, mean_dem, mean_rep, dem_frac, rep_frac = compute_2x2_statewide(
            samples, precinct_pops, group_fraction)

        statewide_rows.append({
            'state':                state_name,
            'racial_group':         group_name,
            'party_of_choice':      poc,
            'confidence':           round(conf, 4),
            'mean_dem_fraction':    round(dem_frac, 6),
            'mean_rep_fraction':    round(rep_frac, 6),
            'mean_dem_votes':       round(mean_dem, 2),
            'mean_rep_votes':       round(mean_rep, 2),
        })

        print(f'      Statewide → party_of_choice={poc}, confidence={conf:.3f}, '
              f'est. dem={mean_dem:,.0f}, rep={mean_rep:,.0f}')

    precinct_out.to_csv(precinct_output_filename, index=False)
    print(f'\n  Saved precinct file: {precinct_output_filename} '
          f'({len(precinct_out)} rows × {len(precinct_out.columns)} cols)')

    statewide_out = pd.DataFrame(statewide_rows)
    statewide_out.to_csv(statewide_output_filename, index=False)
    print(f'  Saved statewide file: {statewide_output_filename} '
          f'({len(statewide_out)} rows × {len(statewide_out.columns)} cols)')

    samples_out = pd.DataFrame(samples_rows)
    samples_out.to_csv(samples_output_filename, index=False)
    print(f'  Saved samples file: {samples_output_filename} '
          f'({len(samples_out)} rows × {len(samples_out.columns)} cols)')

    return precinct_out, statewide_out


print('Pipeline function defined.')

# Debug cell — check valid TwoByTwoEI model names
import inspect
from pyei.two_by_two import TwoByTwoEI
print(inspect.getsource(TwoByTwoEI.fit))

# Cell 7 — Oregon
oregon_precinct, oregon_statewide = run_prepro9_for_state(
    df=oregon_df,
    state_name='Oregon',
    precinct_output_filename='oregon_ei_precinct.csv',
    statewide_output_filename='oregon_ei_statewide.csv',
    samples_output_filename='oregon_ei_samples.csv',
    n_samples=1000,
    n_tune=500,
)

print('\nOregon precinct sample:')
display(oregon_precinct.head(3))
print('\nOregon statewide:')
display(oregon_statewide)

# Cell 8 — South Carolina
sc_precinct, sc_statewide = run_prepro9_for_state(
    df=sc_df,
    state_name='South Carolina',
    precinct_output_filename='south_carolina_ei_precinct.csv',
    statewide_output_filename='south_carolina_ei_statewide.csv',
    samples_output_filename='south_carolina_ei_samples.csv',
    n_samples=1000,
    n_tune=500,
)

print('\nSouth Carolina precinct sample:')
display(sc_precinct.head(3))
print('\nSouth Carolina statewide:')
display(sc_statewide)

# Cell 9 — Download all 4 output files
from google.colab import files

files.download('oregon_ei_precinct.csv')
files.download('oregon_ei_statewide.csv')
files.download('oregon_ei_samples.csv')
files.download('south_carolina_ei_precinct.csv')
files.download('south_carolina_ei_statewide.csv')
files.download('south_carolina_ei_samples.csv')

print('Downloads triggered.')

"""# Analysis of Ecological Inference (EI) Methodology: `finalPrepro-9.ipynb`

This report evaluates the alignment of the provided notebook with the methodology described in the **MGGG VRA-Ensembles paper** and **PyEI documentation**.

## 1. Methodology Confirmation
Your understanding of the VRA-Ensembles methodology is correct. The primary goal is to use Bayesian Ecological Inference (EI) to determine:
1.  **Candidate of Choice (CoC):** The candidate preferred by a specific demographic group.
2.  **Confidence Score:** A measure of certainty that a candidate is the CoC, calculated by observing the frequency of their preference across multiple posterior draws.
3.  **District Effectiveness Score:** A compound score weighting multiple elections by their confidence to determine if a district provides a fair opportunity for minority voters.

## 2. Notebook Analysis: Step-by-Step Alignment

### Step A: Data Preparation and Preprocessing
* **Action:** The notebook aligns demographic data (e.g., White, Black, Asian, Hispanic populations) with election results (Democratic and Republican votes) at the precinct level.
* **Status:** **Complete.** This correctly builds the "Table of Races" required for EI.

### Step B: The EI Model "Run"
* **Action:** The notebook uses `pyei.two_by_two.TwoByTwoEI` to fit Bayesian models using MCMC sampling (e.g., 1500 draws).
* **Status:** **Complete.** The notebook successfully generates the posterior distributions for voter support.

### Step C: Determining Candidate of Choice (CoC)
* **Action:** The notebook identifies the "party of choice" based on the estimated vote fractions.
* **Status:** **Complete.** It assigns a preference based on which candidate receives the highest mean support from a group.

### Step D: The Confidence Score ($C(p)$)
* **Action:** The VRA-Ensembles paper (Footnote 15) defines a specific logistic transformation for confidence:
    $$C(p) = \frac{1}{1 + \exp(18 - 26p)}$$
    Where $p$ is the frequency with which a candidate is observed to be the preferred choice across trials.
* **Status:** **Missing/Manual.** While the notebook includes a column titled `ei_black_precinct_confidence` with high values (e.g., 0.9242), it does not explicitly implement the formula from Footnote 15. The notebook's "confidence" appears to be a different internal metric from the EI model rather than the compound effectiveness weight described in the paper.

## 3. Recommended Next Steps for Full Alignment

To fully match the **VRA-Ensembles** effectiveness scoring, you should add a cell to calculate the specific $C(p)$ score:

1.  **Extract Frequency ($p$):** For each group, calculate the percentage of MCMC samples where the Democratic candidate support is greater than the Republican candidate support.
2.  **Apply Logistic Function:** Use the formula from Footnote 15 to transform $p$ into the weighted confidence score $C(p)$.
3.  **Compound Scoring:** If you have multiple elections, average these $C(p)$ values to find the final **District Effectiveness Score**.

---
**Summary Verdict:** The notebook is a robust implementation of the **PyEI** workflow for identifying voter preferences. To reach the "Effectiveness Score" goals of the **VRA-Ensembles paper**, you must manually implement the logistic confidence transformation described in Footnote 15.

# Conceptual logic based on Footnote 15
# Calculate what percentage of the 1500 draws show Candidate A as the winner among Group X
samples = model.sims['b'] # Support for candidates

p = (samples[:, group_idx, cand_idx] > samples[:, group_idx, other_idx]).mean()

Ayden's prompt to AI:

Refer to this document as to know the aims of the EI in the paper of the VRA redistricting ensembles https://mggg.org/publications/VRA-Ensembles.pdf as well as the PYEI documentation (I think here, may be somewhere else as well) https://github.com/mggg/ecological-inference. The paper goes into detail on the generation of the EI and its purpose, to determine candidates of choice and place a confidence score on them, to get an idea of the candidate of choice for a race. Doing this across multiple runs allows the user to gather the confidence scores, by doing run after run and seeing who was the candidate of choice in each. The runs are performed by creating a table of races and voting for a state/ precinct, somehow filling in those values, described more in the paper and in the documentation.

We also need to calculate the confidence need to be calculated via the formula described in this footnote:
Let the the frequency in a batch of trials with which X is observed to be the preferred candidate. We logistically
transform this to a confidence score using C(p) = 1/(1 + exp(18−26p)) to weight the election in the compound score
of district eﬀectiveness (see Table 1 below). The parameters 18 and 26 were chosen so that an election in which the
draws have Candidate X ahead only 50% of the time should receive almost no weight (because it is a toss-up); but if
Candidate X comes out ahead in, say, 85% of trials, the confidence should be nearly 100%. It is certainly possible to
use other parameters, to skip this step and just use C(p) = pas a measure of confidence, or even to forgo confidence
altogether. Without some factor of this kind, however, the resulting score will have more noise due to cases where
the candidate of choice is uncertain. If we do not strongly down-weight the uncertain elections, we risk a situation
in which just rerunning the EI with identical settings could produce a significantly diﬀerent answer. We discuss this
and other robustness checks in footnote

Check over the relevant sections of the paper (4.12 and footnote 29) and confirm and note the notebooks calculation of confidence
"""