# -*- coding: utf-8 -*-
"""Preproc12.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1G3VpVCAXvccE0kwnEKBUOONftiquZ_BJ
"""

import numpy as np
import pandas as pd
from functools import partial
from enum import Enum, auto
import json

from google.colab import drive
drive.mount('/content/drive')

class State(str, Enum):
    OREGON = "oregon"
    SOUTH_CAROLINA = "south_carolina"
class Race(str, Enum):
    WHITE = "white"
    HISPANIC = "hispanic"
    BLACK = "black"

# Configs
recency_election_scores = 1
minority_effectiveness_score_threshold = .6
in_group_calibration = .5 # The penalty for the preferred candidate not being in_group, always 1 when they are

state = State.SOUTH_CAROLINA
races= [Race.BLACK.value, Race.WHITE.value, Race.HISPANIC.value]

recency = 1
in_group_mapping = {Race.WHITE.value: in_group_calibration, Race.HISPANIC.value: in_group_calibration, Race.BLACK.value: 1}


logit_a = 9
logit_b = logit_a / -2

# MAIN_PATH = f"/content/drive/MyDrive/U4/Spring/CSE416/Seawulf/On Seawulf/{state}"
VAP_PATH = f'/content/drive/MyDrive/U4/Spring/CSE416/Preprocessing/VAP2/my_preprocessing1_out/sw_{state.value}'
PATH_D = f"{VAP_PATH}/data"
PATH_G = f"{VAP_PATH}/graphs"
state_data_df = pd.read_csv(f"{PATH_D}/combined_data.csv")
num_districts= len(state_data_df['district'].unique())
POP_THRESHOLD = None
if any(state_data_df[race].sum() > 400000 for race in races if race.lower() != Race.WHITE.value):
    POP_THRESHOLD = 400000
else:
    POP_THRESHOLD = 200000
minority_sig_groups = [race for race in races if (sum(state_data_df[race])> POP_THRESHOLD and race.lower() != Race.WHITE.value) ]

ei_conf_df = pd.read_csv(f"{PATH_D}/ei_statewide.csv")
ei_conf_all_races = dict(zip(ei_conf_df['racial_group'], ei_conf_df['confidence']))


class Group_Control(Enum):
    DEFAULT = auto()    # Value: 1
    MIN_CAND_VOTE_SHARE = auto()  # Value: 2

group_control = Group_Control.DEFAULT

def prob_conf_conversion(distr_score):

  calibrated_score = 1/(1+np.exp(-(logit_a * distr_score + logit_b)))
  return calibrated_score

def collect_default_group_control(district_id, df,race):
    district_dict = {}
    district_dict[f'{race}_pop'] = df[df['district_id'] ==district_id][race] .sum()
    district_dict['total_pop'] = df[df['district_id'] ==district_id]['total'].sum()
    return district_dict
def evaluate_default_group_control(district_dict, race):
  group_control = min(1,district_dict[f'{race}_pop']/district_dict['total_pop'] * 2)
  return group_control

# def collect_min_cand_group_control(district_id, df,race):
#     district_dict = {}
#     district_dict['democratic_votes'] = df['democratic_votes']
#     pass

def calculate_effectiveness_score(df,ei,in_group, race,group_control_collect_function,
                                  group_control_evaluate_function):
  district_eff_scores= {}
  for district in (range(num_districts)):
    district = district +1

    district_dict = group_control_collect_function(district,df,race)
    district_score = recency * ei[race] * in_group[race]
    group_control = group_control_evaluate_function(district_dict, race)
    district_score *= group_control

    district_calibrated_score = prob_conf_conversion(district_score)
    district_eff_scores[district] = district_calibrated_score


  return district_eff_scores

def calculate_default_eff_score(df,ei,in_group,race):
  return calculate_effectiveness_score(df,ei,in_group, race,
                 collect_default_group_control,
                 evaluate_default_group_control)
# def calculate_minority_candidate_eff_score(distr_dict, df,race):
#   return calculate_effectiveness_score(df,race,
#   )
write_out_path = f"{PATH_D}/state_details.json"
try:
    with open(write_out_path, "r") as f:
        state_extra_details_json = json.load(f)
except (FileNotFoundError, json.JSONDecodeError):
    # Fallback if file doesn't exist or is empty
    state_extra_details_json = {}
if "effective_district_score" not in state_extra_details_json:
    state_extra_details_json["effective_district_score"] = {}
if "effective_district_count" not in state_extra_details_json:
    state_extra_details_json["effective_district_count"] = {}

from pprint import pprint
for race in minority_sig_groups:
    calibrated_scores = calculate_default_eff_score(state_data_df, ei_conf_all_races, in_group_mapping, race)

    clean_scores = {str(dist): float(score) for dist, score in calibrated_scores.items()}


    effective_count = sum(1 for score in clean_scores.values() if score >= minority_effectiveness_score_threshold)

    state_extra_details_json["effective_district_score"][race] = clean_scores
    state_extra_details_json["effective_district_count"][race] = effective_count

# 4. Write back into the original JSON file
with open(write_out_path, "w") as f:
    json.dump(state_extra_details_json, f, indent=4)

print(f"Updated JSON successfully for races: {', '.join(minority_sig_groups)} in {state.value}")

