# -*- coding: utf-8 -*-
"""Preproc5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LYZFp65dde85l9t66PQ1hjiey_Bgfy9Z
"""

import json
import pandas as pd
from enum import Enum
import sys
import numpy as np
import os

from google.colab import drive
drive.mount('/content/drive')

class State(str, Enum):
    OREGON = "oregon"
    SOUTH_CAROLINA = "south_carolina"
class Race(str, Enum):
    WHITE = "white"
    HISPANIC = "hispanic"
    BLACK = "black"
    ASIAN = "asian"

STATE = State.SOUTH_CAROLINA.value
MAIN_PATH = f"/content/drive/MyDrive/U4/Spring/CSE416/Preprocessing/VAP2/my_preprocessing1_out/sw_{STATE}"
PATH_D = f"{MAIN_PATH}/data"
PATH_G = f"{MAIN_PATH}/graphs"
state_data_df = pd.read_csv(f"{PATH_D}/combined_data.csv")
num_districts= len(state_data_df['district'].unique())
races= [Race.BLACK.value, Race.WHITE.value, Race.HISPANIC.value]

POP_THRESHOLD = None
if any(state_data_df[race].sum() > 400000 for race in races if race.lower() != Race.WHITE.value):
    POP_THRESHOLD = 400000
else:
    POP_THRESHOLD = 200000
SIG_MINORITY_GROUPS = [race for race in races if (sum(state_data_df[race])> POP_THRESHOLD and race.lower() != Race.WHITE.value) ]

SIG_RACE_GROUPS = [*SIG_MINORITY_GROUPS, 'white']
EFFECTIVENESS_SCORE_THRESHOLD = .6

### POST-SW GATHERING

# DATA LAYOUT
'''
{

  [
    Votes:
      {
      D_Votes: [],
      R_Votes: []
      },
    Significant Racial Groups:
    {
      race: [population, district] for race in sig_min_group
      white: [population, district]
      total: {district: population} ### Used to easily extract percentage
    }
    eff_scores:
    {
      race: eff_score for race in sig_min_group
      white: eff_score
    }
  ] for _ in range(total_steps)

}
'''

def separate_data_from_run(run_data):
  ## Analyzing electoral data
  # Indices are assumed to be the district number
  # Represent a tie as  += .1 (bounded by # of districts, < 10)
  # Get a sum of the democratic wins in the district plan, can calculate republican by rep_wins[step] = total_distr - dem_wins[step]
  dem_wins_or_ties =[]

  for step in run_data:
    current_step_dem_wins = 0
    for dem_votes, rep_votes in zip(step['Votes']['D_Votes'],step['Votes']['R_Votes']):
      if(dem_votes > rep_votes):
        current_step_dem_wins += 1
      elif (dem_votes == rep_votes):
        current_step_dem_wins += 0.1
    dem_wins_or_ties.append(current_step_dem_wins)
  # print(dem_wins_or_ties, len(dem_wins_or_ties))



  # ### Analyzing racial data
  final_bins ={race:[] for race in SIG_MINORITY_GROUPS}
  maj_min_steps = {race:[] for race in SIG_MINORITY_GROUPS}
  effectiveness_scores = {race:[] for race in SIG_RACE_GROUPS}


  for step in run_data:
    step_bins = []
    for race in (SIG_MINORITY_GROUPS):
      step_race_bins = []
      maj_min_counter = 0
      for distr_race_pop in step['Significant Racial Groups'][race]: # distr_race_pop = [race_population, district]

        min_race_for_distr = distr_race_pop[0]
        district_number = distr_race_pop[1]

        step_race_bins.append(min_race_for_distr)


        if (step['Significant Racial Groups']['total'][f'{district_number}'] - min_race_for_distr < min_race_for_distr):
          maj_min_counter += 1

      effectiveness_scores[race].append(step['eff_scores'][race])
      final_bins[race].append(step_race_bins)
      maj_min_steps[race].append(maj_min_counter)
    # Extra collection for white
    effectiveness_scores[Race.WHITE.value].append(step['eff_scores'][Race.WHITE.value])
  return {
    "dem_wins": dem_wins_or_ties,
    "eff_scores": effectiveness_scores,
    "final_bins": final_bins,
    "maj_min_steps": maj_min_steps,
    "effectiveness_scores": effectiveness_scores
}

def write_separate_data_from_run(prefix_name, steps, **data_args):
    effectiveness_scores = data_args.get('effectiveness_scores', {})
    print(effectiveness_scores)
    EFFECTIVENESS_SCORE_THRESHOLD = 0.6 # Ensure this is defined or passed in

    effective_district_count = {
        race: [
        sum(1 for score in step_scores.values() if score >= EFFECTIVENESS_SCORE_THRESHOLD)
        for step_scores in race_data
        ]
        for race, race_data in effectiveness_scores.items()
    }
    output_bundle = {
        "dem_wins": data_args.get('dem_wins'),
        "eff_scores": data_args.get('eff_scores'),
        "final_bins": data_args.get('final_bins'),
        "maj_min_steps": data_args.get('maj_min_steps'),
        "effectiveness_scores": effectiveness_scores,
        "effective_district_count": effective_district_count
    }


    def npy_serializer(obj):
        if isinstance(obj, (np.int64, np.int32)): return int(obj)
        if isinstance(obj, (np.float64, np.float32)): return float(obj)
        if isinstance(obj, np.ndarray): return obj.tolist()
        raise TypeError(f"Type {type(obj)} not serializable")

    filename = f"{prefix_name}_all_metrics.json"
    with open(filename, 'w') as f:
        json.dump(output_bundle, f, indent=4, default=npy_serializer)

    print(f"Data successfully written to {filename}")


def load_jsonl_data(file_path):
    post_data = []
    try:
        with open(file_path, "r") as f:
            post_data = json.load(f)
        return post_data
    except FileNotFoundError:
        return None


def format_data_from_folder(output_path):
  # Ensure the output directory exists
  if not os.path.exists(output_path):
      os.makedirs(output_path)
  print(output_path)
  files = [f for f in os.listdir(output_path) if f.endswith(".jsonl")]


  if not files:
        print("No .jsonl files found in this directory.")
        return
  for file_name in files:
    if "map" in file_name.lower():
      print(f"Skipping map file: {file_name}")
      continue
    # Skip directories or non-jsonl files
    print(file_name)
    file_path = os.path.join(output_path, file_name)
    base_name, extension = os.path.splitext(file_name)
    post_data = load_jsonl_data(file_path)
    data_from_run = separate_data_from_run(post_data)
    write_separate_data_from_run(output_path + base_name,len(post_data),**data_from_run)
  print("finished")

prefix_out_path = f"{PATH_D}/output/"
format_data_from_folder(prefix_out_path)