# -*- coding: utf-8 -*-
"""Preproc6_2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JeBBz3af6wQU2qf3vdqD2X1lOJszHm-q
"""

import os
import json
import zipfile
import warnings
import geopandas as gpd
import pandas as pd
import numpy as np
import networkx as nx
import maup
import gerrychain

from google.colab import drive
drive.mount('/content/drive/')

# Census race extraction w/ geometry
def get_census_race_data(pl_zip_name):


    # Load the zipped files

    with zipfile.ZipFile(pl_zip_name, 'r') as z:
        # locate files by how its named
        geo_fname   = next(f for f in z.namelist() if "geo2020.pl"     in f.lower())
        seg1_fname = next(f for f in z.namelist() if "000022020.pl" in f.lower()) # VAP data



        with z.open(geo_fname) as fh:
            geo = (pd.read_csv(fh, sep='|', header=None, dtype=str, encoding='latin-1')
                     .apply(lambda s: s.str.strip()))

        with z.open(seg1_fname) as fh:
            race = (pd.read_csv(fh, sep='|', header=None, dtype=str, encoding='latin-1')
                      .apply(lambda s: s.str.strip()))

    blocks = geo[geo[2] == '750'].copy()


    # Per PL spec: LOGRECNO is at geo col 7 and race col 4.
    GEO_LOGRECNO_COL  = 7
    RACE_LOGRECNO_COL = 4


    # Quick sanity-check overlap before continuing
    # geo_set  = set(blocks[GEO_LOGRECNO_COL].astype(str).str.lstrip('0').unique())
    # race_set = set(race[RACE_LOGRECNO_COL].astype(str).str.lstrip('0').unique())
    # overlap  = len(geo_set & race_set)
    # print(f"Bridge verified: {overlap:,} / {len(blocks):,} block LOGRECNOs found in race file.")
    # if overlap < len(blocks) * 0.95:
    #     raise RuntimeError("ERROR ON OVERLAPPING")

    GEOID_COL = 8

    # Remove extra details that make the data not overlap well
    final_geo = pd.DataFrame({
        'LOGRECNO': blocks[GEO_LOGRECNO_COL].astype(str).str.strip().str.lstrip('0'),
        'GEOID':    blocks[GEOID_COL].str.split('US').str[-1]
    })
    print(f" [Census.3] GEOID sample: {final_geo['GEOID'].head().tolist()}")


    # Race extraction from the file
    final_race = pd.DataFrame({
        'LOGRECNO': race[RACE_LOGRECNO_COL].astype(str).str.strip().str.lstrip('0'),
        'total':    pd.to_numeric(race[5],  errors='coerce'),
        'white':    pd.to_numeric(race[80],  errors='coerce'),
        'black':    pd.to_numeric(race[81],  errors='coerce'),
        'asian':    pd.to_numeric(race[83], errors='coerce'),   # FIXED: was race[9]
        'hispanic': pd.to_numeric(race[77], errors='coerce'),    # FIXED: was race[11]
        # Other = total - white - black - hispanic - asian(asian was kept as they seemed to be high in oregon, may not be eligible however)
    }).fillna(0)




    result = final_geo.merge(final_race, on='LOGRECNO', how='inner')

    total_pop = result['total'].sum()
    print(f" {len(result):,} blocks | total pop = {total_pop}")
    print(f" Blocks with pop > 0: {(result['total'] > 0).sum():,}")
    # research shows zeros may be empty areas like water or large parks so not unreasonable

    return result


# State level

def process_state(state_name, uploaded):

    short = "or" if "oregon" in state_name.lower() else "sc"
    fips  = "41" if short == "or" else "45"
    lower = state_name.lower().replace(" ", "_")

    prec_file = next(f for f in uploaded
                     if short in f.lower() and "precincts" in f.lower()
                     and f.endswith('.geojson'))
    precincts = gpd.read_file(uploaded[prec_file]).to_crs("EPSG:3857")
    precincts.geometry = precincts.geometry.buffer(0)
    if 'precinct_id' not in precincts.columns:
        precincts['precinct_id'] = precincts.index.astype(str)
    print(f" Precincts loaded: {len(precincts)} precincts.")



    tiger_url = (f"https://www2.census.gov/geo/tiger/TIGER2020/TABBLOCK20/"
                 f"tl_2020_{fips}_tabblock20.zip")
    # Voting data
    blocks = gpd.read_file(tiger_url).to_crs(precincts.crs)
    blocks.geometry = blocks.geometry.buffer(0)

    pl_zip = next(f for f in uploaded
                  if short in f.lower() and "2020.pl.zip" in f.lower())
    race_table = get_census_race_data(uploaded[pl_zip])

    geoid_col = 'GEOID20' if 'GEOID20' in blocks.columns else 'GEOID'
    blocks[geoid_col] = blocks[geoid_col].astype(str).str.zfill(15)
    # race_table['GEOID'] is already a clean 15-digit string from get_census_race_data
    blocks = blocks.merge(race_table[['GEOID','total','white','black','asian','hispanic']],
                          left_on=geoid_col, right_on='GEOID', how='inner')

    assignment = maup.assign(blocks.geometry, precincts.geometry)
    # print(precincts.keys())

    race_cols  = ['total', 'white', 'black', 'asian', 'hispanic']
    
    precincts[race_cols] = (blocks[race_cols]
                            .groupby(assignment)
                            .sum()
                            .reindex(precincts.index)
                            .fillna(0)
                            .astype(int))
    precincts['other'] = (precincts['total']
                     - precincts['white']
                     - precincts['black']
                     - precincts['asian']
                     - precincts['hispanic']).clip(lower=0)
    race_cols.append('other')


    # Precinct -> Districts
    dist_file = next(f for f in uploaded
                     if lower in f.lower() and 'district' in f.lower()
                     and f.endswith('.geojson'))
    districts = gpd.read_file(uploaded[dist_file]).to_crs(precincts.crs)
    districts.geometry = districts.geometry.buffer(0)

    # Use precinct centroid for assignment for safety
    prec_centroids = precincts.copy()
    prec_centroids.geometry = prec_centroids.geometry.centroid
    dist_join = gpd.sjoin(prec_centroids, districts, how='left', predicate='within')
    

    dist_col = 'CD118FP' if 'CD118FP' in districts.columns else 'district'
    precincts['district_id'] = dist_join[dist_col].fillna("0").values


    state_abbr = 'OR' if 'oregon' in state_name.lower() else 'SC'
    results_file = next(f for f in uploaded
                        if state_abbr in f.upper() and 'precincts-with-results' in f
                        and f.endswith('.csv'))

    results_df = pd.read_csv(uploaded[results_file])

    # The GeoJSON precinct_id should match results_df GEOID.
    # If the anchor GeoJSON doesn't carry GEOID, align by position or add a
    # county-precinct key that matches the CSV format.
    if 'GEOID' in precincts.columns:
        election_df = (precincts[['precinct_id', 'GEOID']]
                       .merge(results_df[['GEOID','votes_dem','votes_rep','votes_total']],
                              on='GEOID', how='left'))
    else:
        # Fallback: CSV and GeoJSON rows may be in the same precinct order...
        print(" No 'GEOID' column found in precinct GeoJSON. "
              "Aligning election CSV by row order (verify this is correct).")
        election_df = pd.DataFrame({
            'precinct_id':       precincts['precinct_id'].values,
            'democratic_votes':  results_df['votes_dem'].values,
            'republican_votes':  results_df['votes_rep'].values,
            'total_votes':       results_df['votes_total'].values
        })

    election_df = election_df.rename(columns={
        'votes_dem': 'democratic_votes',
        'votes_rep': 'republican_votes',
        'votes_total': 'total_votes'
    }).fillna(0)
    election_df[['democratic_votes','republican_votes','total_votes']] = (
        election_df[['democratic_votes','republican_votes','total_votes']].astype(int)
    )
    print(f"  ✅ Election data loaded. "
          f"Total dem votes: {election_df['democratic_votes'].sum():,.0f}  "
          f"Total rep votes: {election_df['republican_votes'].sum():,.0f}")


    if "oregon" in state_name.lower():
        reps = {
            1: {"name": "Suzanne Bonamici", "party": "Democrat",    "race": "White",    "margin": 0.58},
            2: {"name": "Cliff Bentz",       "party": "Republican",  "race": "White",    "margin": 0.62},
            3: {"name": "Maxine Dexter",     "party": "Democrat",    "race": "White",    "margin": 0.71},
            4: {"name": "Val Hoyle",         "party": "Democrat",    "race": "White",    "margin": 0.52},
            5: {"name": "Janelle Bynum",     "party": "Democrat",    "race": "Black",    "margin": 0.51},
            6: {"name": "Andrea Salinas",    "party": "Democrat",    "race": "Hispanic", "margin": 0.55},
        }
    else:  # SC
        reps = {
            1: {"name": "Nancy Mace",        "party": "Republican",  "race": "White",    "margin": 0.55},
            2: {"name": "Joe Wilson",        "party": "Republican",  "race": "White",    "margin": 0.60},
            3: {"name": "Jeff Duncan",       "party": "Republican",  "race": "White",    "margin": 0.68},
            4: {"name": "William Timmons",   "party": "Republican",  "race": "White",    "margin": 0.62},
            5: {"name": "Ralph Norman",      "party": "Republican",  "race": "White",    "margin": 0.59},
            6: {"name": "Jim Clyburn",       "party": "Democrat",    "race": "Black",    "margin": 0.65},
            7: {"name": "Russell Fry",       "party": "Republican",  "race": "White",    "margin": 0.58},
        }

    incumbent_rows = []
    for _, row in precincts.iterrows():
        try:
            dist_num = int(row['district_id'])
        except (ValueError, TypeError):
            dist_num = 0
        rep = reps.get(dist_num, {"name": "Unknown", "party": "Unknown",
                                  "race": "Unknown", "margin": 0.0})
        incumbent_rows.append({
            'precinct_id':      row['precinct_id'],
            'district':         dist_num,
            'representative':   rep['name'],
            'party':            rep['party'],
            'incumbent_race':   rep['race'],
            'margin':           rep['margin']
        })
    incumbent_df = pd.DataFrame(incumbent_rows)

    print("\n📍 [7/7] Writing output files...")
    VAP_DIR = '/content/drive/MyDrive/U4/Spring/CSE416/Preprocessing/VAP2/my_preprocessing1_out/'
    output_dir = f'{VAP_DIR}/{lower}'
    os.makedirs(output_dir, exist_ok=True)


    precincts[['precinct_id', 'district_id', 'geometry']].to_file(
        f'{output_dir}/precincts.geojson', driver='GeoJSON')


    demo_df = precincts[['precinct_id'] + race_cols].copy()
    demo_df.to_csv(f'{output_dir}/demographics.csv', index=False)


    election_df.to_csv(f'{output_dir}/election_2024.csv', index=False)


    incumbent_df.to_csv(f'{output_dir}/incumbents.csv', index=False)


    combined = (demo_df
                .merge(election_df.drop(columns=['GEOID'], errors='ignore'),
                       on='precinct_id', how='left')
                .merge(incumbent_df,
                       on='precinct_id', how='left'))
    combined.to_csv(f'{output_dir}/combined.csv', index=False)




import glob

DATA_DIR = "/content"   

uploaded = {}
for path in glob.glob(os.path.join(DATA_DIR, "**"), recursive=True):
    if os.path.isfile(path):
        uploaded[os.path.basename(path)] = path
# print(uploaded.keys())
for state in ["Oregon", "South Carolina"]:
    process_state(state, uploaded)




# ============================================
# PREPRO-6 FINAL – Generate SeaWulf / GerryChain Files
# CSE416 Spring 2026
# ============================================
#
# High-Level Flow:
#   For each state (Oregon, South Carolina):
#   1. LOAD      – Read all Prepro-1 outputs (precincts GeoJSON + CSVs).
#   2. MERGE     – Join demographics, elections, and incumbents onto the
#                  GeoDataFrame so every precinct row has all attributes.
#   3. REPAIR    – Apply maup.smart_repair() to fix topology before any
#                  graph work (slivers, gaps, invalid geometries, etc.).
#   4. GRAPH     – Build the adjacency graph via gerrychain.Graph.from_geodataframe()
#                  with rook contiguity — the canonical MGGG method.
#                  All GeoDataFrame columns become node attributes automatically.
#   5. SERIALIZE – Two graph files:
#                    • precinct_graph.json          (no geometry – fast, for SeaWulf runs)
#                    • precinct_graph_with_geo.json (geometry as GeoJSON – for viz)
#                  The companion precincts.geojson from Prepro-1 can be joined to
#                  any post-run output by matching precinct_id, so the viz GeoJSON
#                  doubles as the authoritative geometry reference.
#   6. ADJACENCY – Human-readable adjacency list text file.
#   7. DATA CSVs – Copy CSVs for reference / debugging.
#
# Key Bugs Fixed from Original PREPRO-6:
#   • Graph construction: replaced manual NX + .touches() loop with
#     gerrychain.Graph.from_geodataframe(adjacency='rook').  The manual
#     loop using .touches() misses a large fraction of shared-edge pairs
#     due to floating-point topology irregularities.
#   • Node attributes: the old graph only stored centroid_x/y.  GerryChain
#     needs all race + election + district columns as node attributes.
#     from_geodataframe() copies all GeoDataFrame columns to nodes via
#     cols_to_add automatically.
#   • Serialization: replaced pickle (Python-version-dependent, not portable
#     across machines) with gerrychain's own graph.to_json() which uses the
#     NetworkX adjacency-data JSON format that from_json() can reload exactly.
#   • Two output versions: lightweight (no geometry, ~10× smaller) for the
#     compute nodes, and a geometry-embedded version for visualization pipelines.
#
# GeoJSON / Geometry separation note:
#   GerryChain does NOT need geometry during a MCMC run.  The geometry lives
#   in precincts.geojson.  After a run, join district assignments back to the
#   GeoJSON by precinct_id for choropleth rendering.
#
# ============================================

# ----------------------------------------------------------
# Dependencies (run once in Colab):
# !pip install gerrychain maup geopandas pandas numpy networkx shapely -q
# ----------------------------------------------------------

import os
import json
import zipfile
import warnings
import geopandas as gpd
import pandas as pd
import numpy as np
import networkx as nx
import maup
import gerrychain

warnings.filterwarnings('ignore')

# ----------------------------------------------------------
# Output directory layout
# ----------------------------------------------------------
# seawulf_data/
#   oregon/
#     graphs/
#       precinct_graph.json              ← lightweight (no geometry) for SeaWulf
#       precinct_graph_with_geo.json     ← geometry-embedded for visualization
#       adjacency_list.txt               ← human-readable adjacency list
#     data/
#       precincts.geojson                ← full GeoDataFrame with all attributes
#       combined_data.csv                ← flat CSV (no geometry)
#       election_2024.csv
#       demographics.csv
#       incumbents.csv
#   south_carolina/  (same structure)

for state_dir in ['seawulf_data/oregon', 'seawulf_data/south_carolina']:
    os.makedirs(f'{state_dir}/graphs', exist_ok=True)
    os.makedirs(f'{state_dir}/data',   exist_ok=True)




PREPRO1_DIR = f'/content/drive/MyDrive/U4/Spring/CSE416/Preprocessing/VAP2/my_preprocessing1_out'


def process_state(state_name: str):

    lower     = state_name.lower().replace(" ", "_")
    state_dir = f'/content/drive/MyDrive/U4/Spring/CSE416/Preprocessing/VAP2/my_preprocessing1_out/sw_{lower}'
    base      = f'{PREPRO1_DIR}/{lower}'


    precinct_gdf = gpd.read_file(f'{base}/precincts.geojson')
    election_df  = pd.read_csv(f'{base}/election_2024.csv')
    demo_df      = pd.read_csv(f'{base}/demographics.csv')
    incumbent_df = pd.read_csv(f'{base}/incumbents.csv')


    print("\n📍 [2/7] Merging attributes onto GeoDataFrame...")

    precinct_gdf.loc[:, 'precinct_id'] = precinct_gdf['precinct_id'].astype(str).values
    demo_df.loc[:,      'precinct_id'] = demo_df['precinct_id'].astype(str).values
    election_df.loc[:,  'precinct_id'] = election_df['precinct_id'].astype(str).values
    incumbent_df.loc[:, 'precinct_id'] = incumbent_df['precinct_id'].astype(str).values

    # Log dtypes so future mismatches are immediately visible
    print(f"  precinct_id dtypes: "
          f"gdf={precinct_gdf['precinct_id'].dtype}  "
          f"demo={demo_df['precinct_id'].dtype}  "
          f"election={election_df['precinct_id'].dtype}  "
          f"incumbent={incumbent_df['precinct_id'].dtype}")

    gdf_cols       = set(precinct_gdf.columns) - {'precinct_id', 'geometry'}
    demo_cols      = [c for c in demo_df.columns      if c not in gdf_cols | {'precinct_id'}]
    election_cols  = [c for c in election_df.columns  if c not in gdf_cols | {'precinct_id'}]
    incumbent_cols = [c for c in incumbent_df.columns if c not in gdf_cols | {'precinct_id'}]

    gdf = (precinct_gdf
           .merge(demo_df[     ['precinct_id'] + demo_cols],      on='precinct_id', how='left')
           .merge(election_df[ ['precinct_id'] + election_cols],  on='precinct_id', how='left')
           .merge(incumbent_df[['precinct_id'] + incumbent_cols], on='precinct_id', how='left'))


    gdf['district_id'] = pd.to_numeric(gdf['district_id'], errors='coerce').fillna(0).astype(int)


    print(f"  ✓ Combined GDF: {len(gdf):,} rows × {gdf.shape[1]} columns")
    print(f"  ✓ Columns: {gdf.columns.tolist()}")



    if lower == 'oregon':
        utm_crs = 'EPSG:32610'   
    else:
        utm_crs = 'EPSG:32617'   
    gdf = gdf.to_crs(utm_crs)


    print("start maup.smart_repair")
    # Ensure RangeIndex going in — defensive reset in case any earlier step
    # (e.g. a merge) left a non-contiguous index.
    gdf = gdf.reset_index(drop=True)

    gdf_repaired = maup.smart_repair(
        gdf,
        snapped=True,
        snap_precision=8,
        fill_gaps=True,
        fill_gaps_threshold=0.05,

    )
    if len(gdf_repaired) != len(gdf):
        print(f"  ⚠️  Row count changed by repair: {len(gdf)} → {len(gdf_repaired)} "
              f"({len(gdf) - len(gdf_repaired)} fragments removed)")

    # Now safe to promote precinct_id to index for GerryChain node labelling.
    gdf_repaired = gdf_repaired.set_index('precinct_id')
    print(f"  ✓ Repair complete: {len(gdf_repaired):,} precincts retained")


    graph = gerrychain.Graph.from_geodataframe(
        gdf_repaired,
        adjacency='rook',
        cols_to_add=None,      # add ALL columns as node attributes
        reproject=False,       # already in UTM
        ignore_errors=False    # fail loudly on remaining invalid geometries
    )

    print(f" Nodes:     {graph.number_of_nodes():,}")
    print(f" Edges:     {graph.number_of_edges():,}")

    # Island check – degree-0 nodes break GerryChain runs
    islands = graph.islands
    if islands:
        print(f"  ⚠️  Islands (degree-0 nodes): {len(islands)} – "
              f"these will cause GerryChain to fail. IDs: {list(islands)[:10]}...")
        print("     Consider a second maup.smart_repair() pass or manual review.")
    else:
        print("  ✓ No islands detected.")

    is_connected = nx.is_connected(graph)
    print(f"  ✓ Connected: {is_connected}")
    if not is_connected:
        n_comp = nx.number_connected_components(graph)
        print(f"  ⚠️  {n_comp} connected components. "
              f"GerryChain requires a connected graph. "
              f"Flag for future repair pass.")

    graph_path_light = f'{state_dir}/graphs/precinct_graph.json'
    graph_path_geo   = f'{state_dir}/graphs/precinct_graph_with_geo.json'

    graph.to_json(graph_path_light, include_geometries_as_geojson=False)
    print(f"  ✓ Lightweight graph: {graph_path_light}  "
          f"({os.path.getsize(graph_path_light):,} bytes)")

    graph.to_json(graph_path_geo, include_geometries_as_geojson=True)
    print(f"  ✓ Geo-embedded graph: {graph_path_geo}  "
          f"({os.path.getsize(graph_path_geo):,} bytes)")

    # Human-readable adjacency list (sorted for reproducibility)
    adj_path = f'{state_dir}/graphs/adjacency_list.txt'
    with open(adj_path, 'w') as f:
        for node in sorted(graph.nodes()):
            neighbors = sorted(graph.neighbors(node))
            f.write(f"{node}: {','.join(map(str, neighbors))}\n")
    print(f"  ✓ Adjacency list: {adj_path}")



    # Full GeoDataFrame (with all attributes + geometry)
    gdf_repaired.reset_index().to_file(f'{state_dir}/data/precincts.geojson',
                                        driver='GeoJSON')

    # Flat CSVs (no geometry)
    flat_df = gdf_repaired.reset_index().drop(columns=['geometry'])
    flat_df.to_csv(f'{state_dir}/data/combined_data.csv', index=False)

    # Individual source CSVs (for reference)
    election_df.to_csv( f'{state_dir}/data/election_2024.csv', index=False)
    demo_df.to_csv(     f'{state_dir}/data/demographics.csv',  index=False)
    incumbent_df.to_csv(f'{state_dir}/data/incumbents.csv',    index=False)

    # Metadata JSON
    metadata = {
        'state':             state_name,
        'num_precincts':     len(gdf_repaired),
        'num_districts':     int(gdf_repaired['district_id'].nunique()),
        'graph_nodes':       graph.number_of_nodes(),
        'graph_edges':       graph.number_of_edges(),
        'graph_connected':   is_connected,
        'islands':           list(islands),
        'node_attributes':   [k for k in dict(list(graph.nodes(data=True))[0][1]).keys()],
        'crs':               str(gdf_repaired.crs),
        'generated_date':    pd.Timestamp.now().strftime('%Y-%m-%d %H:%M:%S'),
    }
    with open(f'{state_dir}/metadata.json', 'w') as fh:
        json.dump(metadata, fh, indent=2)

    print(f"  ✓ All files written to '{state_dir}/'")
    print(f"\n✅ {state_name} complete.  Node attributes: {metadata['node_attributes']}")

process_state("Oregon")
process_state("South Carolina")



for state in ['oregon', 'south_carolina']:
    zip_name = f'{state}_seawulf_data.zip'
    with zipfile.ZipFile(zip_name, 'w', zipfile.ZIP_DEFLATED) as z:
        for root, _, fnames in os.walk(f'seawulf_data/{state}'):
            for fname in fnames:
                full = os.path.join(root, fname)
                arcname = os.path.relpath(full, 'seawulf_data')
                z.write(full, arcname)



# Checking over values of outputted graph, missing geometries


# VAP_DIR = '/content/drive/MyDrive/U4/Spring/CSE416/Preprocessing/VAP2/my_preprocessing1_out/'
# PP_OR_DIR = f'{VAP_DIR}/oregon'
# PP_SC_DIR = f'{VAP_DIR}/south_carolina'

# SW_OR_DIR = f'{VAP_DIR}/sw_oregon'
# SW_SC_DIR = f'{VAP_DIR}/sw_south_carolina'

# or_graph = gerrychain.Graph.from_json(f'{SW_OR_DIR}/graphs/precinct_graph.json')
# or_partition = gerrychain.Partition(or_graph, assignment='district_id')

# or_gdf = gpd.read_file(f'{SW_OR_DIR}/data/precincts.geojson').set_index('precinct_id')
# or_gdf['new_district'] = pd.Series(dict(or_partition.assignment))
# or_gdf.plot(column='new_district')

# from gerrychain.partition import assignment
# # Trying to see where the islands are
# or_graph.islands #323, 958
# islands_gdf = or_gdf.loc[list(or_graph.islands)]
# list(islands_gdf['geometry'].head())
# # [<POLYGON EMPTY>, <POLYGON EMPTY>]


# # islands_gdf.plot(column= 'district_id',categorical=True, legend=True, cmap='tab10', figsize=(10, 10))
# # # 1. Create a deep copy
# # updated_gdf = or_gdf.copy()

# # # 2. Determine the new unique ID
# # # Assuming numeric IDs; if they are strings, use something like 'New District'
# # new_id = 7

# # # 3. Apply the change to the copy only
# # updated_gdf.loc[list(or_graph.islands), 'district_id'] = new_id

# # updated_gdf = updated_gdf[updated_gdf['district_id'].isin([3,4])] # Exclude: 2
# # updated_gdf.plot(column='district_id', categorical=True, legend=True, cmap='tab10', figsize=(10, 10))
# # print(f"Original unique IDs: {or_gdf['district_id'].nunique()}")
# # print(f"New unique IDs: {updated_gdf['district_id'].nunique()}")
# # # or_gdf['district_id'].unique()
# # islands_gdf.head()

from google.colab import drive
drive.mount('/content/drive/')

# Find if a precinct is missing in geojsons
# combined_pp = pd.read_csv(f'{PP_OR_DIR}/combined.csv')
# gdf = gpd.read_file(f'{PP_OR_DIR}/precincts.geojson')
# master_precincts = list(combined_pp['precinct_id'])
# geo_precincts = list(gdf['precinct_id'].astype(int))

# missing_precincts_gtoc = [precinct for precinct in master_precincts if precinct not in geo_precincts]
# missing_precincts_ctog = [precinct for precinct in geo_precincts if precinct not in master_precincts]
# print(f"Missing in GeoJSON: {missing_precincts_gtoc}")
# print(f"Missing in Combined: {missing_precincts_ctog}")
# # Missing in GeoJSON: [] Everything is there
# # Missing in Combined: []
# print ("master len", len(master_precincts)) #1303
# print ("geo len", len(geo_precincts)) #1303

# islands_gdf = gdf.loc[gdf['precinct_id'].isin(or_graph.islands)]
# islands_gdf.head()
# print(islands_gdf.geometry)
# 323    POLYGON ((-13739469.078 5271511.106, -13739469...
# 958    POLYGON ((-13643072.852 5708225.482, -13643073...

import os, json
import geopandas as gpd
import pandas as pd
import shapely
from shapely.ops import unary_union
import gerrychain

PP_OR_DIR  = '/content/drive/MyDrive/U4/Spring/CSE416/Preprocessing/VAP2/my_preprocessing1_out/oregon'
SW_OR_DIR  = '/content/drive/MyDrive/U4/Spring/CSE416/Preprocessing/VAP2/my_preprocessing1_out/sw_oregon'
SW_SC_DIR = '/content/drive/MyDrive/U4/Spring/CSE416/Preprocessing/VAP2/my_preprocessing1_out/sw_south_carolina'
MIN_ROOK_LENGTH_M = 1.0    
GAP_M             = 60.96  # 200 ft in metres



graph = gerrychain.Graph.from_json(f'{SW_OR_DIR}/graphs/precinct_graph.json')
repaired_gdf = gpd.read_file(f'{SW_OR_DIR}/data/precincts.geojson').set_index('precinct_id')

# Confirm islands
islands = set(graph.islands)
print(f"  Islands (degree-0 nodes): {sorted(islands)}")

NODE_ID_TYPE = str

def to_node_id(x):
    """Cast x to str to match GerryChain graph node IDs."""
    return NODE_ID_TYPE(x)

# Normalise both GDF indices to str so all .loc and graph operations are type-consistent.
repaired_gdf.index = repaired_gdf.index.map(to_node_id)
print(f"  Node IDs normalised to str. Sample graph node: {repr(next(iter(graph.nodes())))}")


original_gdf = (gpd.read_file(f'{PP_OR_DIR}/precincts.geojson')
                   .set_index('precinct_id'))


# Reproject the original GDF to match the other as it was changed before MAUP
utm_crs = repaired_gdf.crs
original_gdf = original_gdf.to_crs(utm_crs)

original_gdf.index = original_gdf.index.map(to_node_id)

for isl in sorted(islands):
    orig_geom = original_gdf.loc[isl, 'geometry']

    # Patch the repaired GDF with the original geometry
    repaired_gdf.loc[isl, 'geometry'] = orig_geom


def island_neighbor_length(g1, g2, min_shared_m):

    # Case 1: exact shared edge
    sp = shapely.shared_paths(g1.boundary, g2.boundary)
    shared = sum(geom.length for geom in sp.geoms)
    if shared >= min_shared_m:
        return shared

    # Case 2: absorbed overlap
    g1_in_g2 = g1.boundary.intersection(g2)
    g2_in_g1 = g2.boundary.intersection(g1)
    overlap_contact = max(g1_in_g2.length, g2_in_g1.length)
    if overlap_contact >= min_shared_m:
        return overlap_contact

    # Case 3: micro-gap from coordinate imprecision between source files
    zone = (g1.boundary.buffer(2.5).intersection(g2.boundary.buffer(2.5)))
    if not zone.is_empty:
        micro = min(g1.boundary.intersection(zone).length,
                    g2.boundary.intersection(zone).length)
        if micro >= min_shared_m:
            return micro

    return max(shared, overlap_contact)



# Build STRtree over all non-empty geometries for fast candidate lookup
from shapely.strtree import STRtree
all_ids   = [to_node_id(x) for x in repaired_gdf.index]
all_geoms = list(repaired_gdf.geometry)
sindex    = STRtree(all_geoms)

new_edges = []

for isl in sorted(islands):
    isl_pos  = all_ids.index(isl)
    isl_geom = all_geoms[isl_pos]

    candidate_positions = sindex.query(isl_geom.buffer(5.0))

    rook_neighbors = []
    for pos in candidate_positions:
        cand = all_ids[pos]
        if cand == isl:
            continue
        cand_geom = all_geoms[pos]
        eff_len = island_neighbor_length(isl_geom, cand_geom, MIN_ROOK_LENGTH_M)
        if eff_len >= MIN_ROOK_LENGTH_M:
            rook_neighbors.append(cand)

    print(f"  Island {isl} — {len(rook_neighbors)} neighbors found: {sorted(rook_neighbors)}")

    for nb in rook_neighbors:
        new_edges.append((isl, nb))

for u, v in new_edges:
    if not graph.has_edge(u, v):
        graph.add_edge(u, v)
        print(f"  + edge ({u}, {v})")


for isl in sorted(islands):
    if isl in graph.nodes:
        graph.nodes[isl]['geometry'] = repaired_gdf.loc[isl, 'geometry']
        cx = repaired_gdf.loc[isl, 'geometry'].centroid.x
        cy = repaired_gdf.loc[isl, 'geometry'].centroid.y
        graph.nodes[isl]['centroid_x'] = cx
        graph.nodes[isl]['centroid_y'] = cy

remaining_islands = set(graph.islands)
print(f"\n  Islands remaining after patch: {sorted(remaining_islands)}")

import networkx as nx
print(f"  Graph connected: {nx.is_connected(graph)}")




repaired_gdf.reset_index().to_file(f'{SW_OR_DIR}/data/precincts.geojson', driver='GeoJSON')
print(f"  ✓ precincts.geojson updated")


graph.to_json(f'{SW_OR_DIR}/graphs/precinct_graph.json',
              include_geometries_as_geojson=False)
print(f"  ✓ precinct_graph.json updated")


graph.to_json(f'{SW_OR_DIR}/graphs/precinct_graph_with_geo.json',
              include_geometries_as_geojson=True)



with open(f'{SW_OR_DIR}/graphs/adjacency_list.txt', 'w') as f:
    for node in sorted(graph.nodes()):
        neighbors = sorted(graph.neighbors(node))
        f.write(f"{node}: {','.join(map(str, neighbors))}\n")



repaired_gdf.reset_index().drop(columns=['geometry']).to_csv(
    f'{SW_OR_DIR}/data/combined_data.csv', index=False)



meta_path = f'{SW_OR_DIR}/metadata.json'
if os.path.exists(meta_path):
    with open(meta_path) as fh:
        meta = json.load(fh)
    meta['graph_edges']   = graph.number_of_edges()
    meta['graph_connected'] = nx.is_connected(graph)
    meta['islands']         = list(set(graph.islands))
    meta['patch_applied']   = True
    meta['patched_nodes']   = sorted(islands)
    with open(meta_path, 'w') as fh:
        json.dump(meta, fh, indent=2)


# Checking on missing data
# graph.nodes['198']



# repaired_gdf.head()
# graph.islands # '323', '958'
# graph.nodes # All strings

# # islands2_gdf = repaired_gdf.loc[list(graph.islands)]
# list(islands2_gdf['geometry'].head())

# [<POLYGON ((534517.561 5043935.497, 534517.205 5043935.495, 534494.805 504393...>,
#  <POLYGON ((465311.916 4731319.668, 465311.914 4731319.281, 465311.891 473131...>]


GAP_TOLERANCE_FT = 200.0   # maximum gap between two boundaries to still be neighbors
MIN_SHARED_FT    = 200.0   # minimum parallel boundary run to count as rook adjacency

# Convert to metres (UTM CRS)
FT_TO_M        = 0.3048
GAP_TOLERANCE_M = GAP_TOLERANCE_FT * FT_TO_M   # 60.96 m
MIN_SHARED_M    = MIN_SHARED_FT    * FT_TO_M   # 60.96 m

def fuzzy_rook(g1, g2, gap_m: float, min_shared_m: float) -> (bool, float):

    def _longest_run(geom) -> float:
        if geom.is_empty:
            return 0.0
        if geom.geom_type == 'LineString':
            return geom.length
        if geom.geom_type == 'MultiLineString':
            return max(g.length for g in geom.geoms)

        runs = [g.length for g in geom.geoms
                if g.geom_type in ('LineString', 'MultiLineString')]
        return max(runs) if runs else 0.0


    sp = shapely.shared_paths(g1.boundary, g2.boundary)
    shared = sum(geom.length for geom in sp.geoms)
    if shared >= min_shared_m:
        return (True, shared)          

    seg1 = g1.boundary.intersection(g2.buffer(gap_m))   
    seg2 = g2.boundary.intersection(g1.buffer(gap_m))   

    run1 = _longest_run(seg1)
    run2 = _longest_run(seg2)
    min_run = min(run1, run2)
    if min_run >= min_shared_m:
        return (True, min_run)
    return (False, min_run)

def build_fuzzy_graph(state_dir: str, state_label: str):

    graph = gerrychain.Graph.from_json(f'{state_dir}/graphs/precinct_graph.json')
    gdf   = gpd.read_file(f'{state_dir}/data/precincts.geojson').set_index('precinct_id')

    NODE_ID_TYPE = str
    gdf.index    = gdf.index.map(NODE_ID_TYPE)
    print(f"  Index normalised to str. Sample node: {repr(next(iter(graph.nodes())))}")


    if gdf.crs is None or gdf.crs.is_geographic:
        raise ValueError(
            "CRS must be a projected (metre-unit) system. "
        )

    empty_mask = gdf.geometry.is_empty | gdf.geometry.isna()
    n_empty    = empty_mask.sum()
    if n_empty:
        print(f"  ⚠️  {n_empty} empty geometries — run island patch first: "
              f"{gdf.index[empty_mask].tolist()}")

    valid_gdf = gdf[~empty_mask].copy()
    geoms     = list(valid_gdf.geometry)
    ids       = [NODE_ID_TYPE(x) for x in valid_gdf.index]

    sindex = STRtree(geoms)

    import time
    t0 = time.time()

    new_edges       = []
    skipped_corners = 0
    already_present = 0
    pairs_checked   = 0

    for i, (pid, geom) in enumerate(zip(ids, geoms)):

        candidates = sindex.query(geom.buffer(GAP_TOLERANCE_M))

        for j in candidates:
            if j <= i:
                continue   # avoid double-counting; (i,j) only processed once

            other_pid  = ids[j]
            other_geom = geoms[j]
            pairs_checked += 1

            # Skip if edge already in graph
            if graph.has_edge(pid, other_pid):
                already_present += 1
                continue

            # Explicit two-condition AND (spec: >= 200ft shared AND within 200ft)
            is_neighbor, edge_length = fuzzy_rook(geom, other_geom, GAP_TOLERANCE_M, MIN_SHARED_M)

            if is_neighbor:
                new_edges.append((pid, other_pid,edge_length))
            else:
                skipped_corners += 1

    elapsed = time.time() - t0

    for u, v, shared_len in new_edges:
        graph.add_edge(u, v, shared_perim=shared_len, fuzzy_rook=True)

    if new_edges:
        sample = new_edges[:5]
        print(f"  Sample new edges: {[(u,v) for u,v,_ in sample]}")

    remaining_islands = set(graph.islands)

    if not nx.is_connected(graph):
        n_comp = nx.number_connected_components(graph)
        print(f"  ⚠️  {n_comp} components — disconnection not caused by geometry.")


    graph.to_json(f'{state_dir}/graphs/precinct_graph.json',
                  include_geometries_as_geojson=False)


    graph.to_json(f'{state_dir}/graphs/precinct_graph_with_geo.json',
                  include_geometries_as_geojson=True)


    with open(f'{state_dir}/graphs/adjacency_list.txt', 'w') as f:
        for node in sorted(graph.nodes()):
            neighbors = sorted(graph.neighbors(node))
            f.write(f"{node}: {','.join(map(str, neighbors))}\n")


    # Edge audit CSV — useful for reviewing which edges were added by fuzzy pass
    if new_edges:
        audit = pd.DataFrame(new_edges, columns=['precinct_a', 'precinct_b', 'length'])
        audit.to_csv(f'{state_dir}/graphs/fuzzy_rook_new_edges.csv', index=False)


    # Update metadata
    meta_path = f'{state_dir}/metadata.json'
    if os.path.exists(meta_path):
        with open(meta_path) as fh:
            meta = json.load(fh)
        meta['graph_edges']         = graph.number_of_edges()
        meta['graph_connected']     = nx.is_connected(graph)
        meta['islands']             = list(remaining_islands)
        meta['fuzzy_rook_applied']  = True
        meta['fuzzy_rook_gap_ft']   = GAP_TOLERANCE_FT
        meta['fuzzy_rook_min_ft']   = MIN_SHARED_FT
        meta['fuzzy_rook_new_edges']= len(new_edges)
        with open(meta_path, 'w') as fh:
            json.dump(meta, fh, indent=2)
        print(f"  ✓ metadata.json")

    print(f"\n✅ {state_label} done.  "
          f"Edges: {graph.number_of_edges():,}  "
          f"(+{len(new_edges)} fuzzy)  "
          f"Connected: {nx.is_connected(graph)}")



build_fuzzy_graph(SW_OR_DIR, "Oregon")
build_fuzzy_graph(SW_SC_DIR, "South Carolina")