spring.application.name=braves-server
server.port=8080

# MongoDB
spring.data.mongodb.uri=${MONGODB_URI:mongodb://localhost:27017/cse416_braves}

# API docs
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

# Seed loader
app.seed.enabled=${APP_SEED_ENABLED:true}
app.seed.root-path=${APP_SEED_ROOT_PATH:}

# JSON behavior
spring.jackson.default-property-inclusion=non_null

# HTTP response compression
server.compression.enabled=true
server.compression.min-response-size=1024
server.compression.mime-types=application/json,application/geo+json,application/javascript,text/plain,text/html,text/xml,text/css
