# -*- coding: utf-8 -*-
"""MyGerryChain

Automatically generated by Colab.

"""



from gerrychain.updaters import Tally, cut_edges
from gerrychain import (Partition, Graph, MarkovChain,
                        updaters, constraints, accept)
from gerrychain.proposals import recom
from gerrychain.tree import bipartition_tree
from gerrychain import GeographicPartition
from gerrychain.accept import always_accept
from gerrychain import Election
from gerrychain.constraints import contiguous
from functools import partial
import pandas as pd
import geopandas as gpd
import os
import sys
import pprint
import json
import hashlib
import random
import ray
import numpy as np
from enum import Enum



class State(str, Enum):
    OREGON = "oregon"
    SOUTH_CAROLINA = "south_carolina"
class Race(str, Enum):
    WHITE = "white"
    HISPANIC = "hispanic"
    BLACK = "black"
    ASIAN = "asian"


# Global "Macros"
state_name = sys.argv[1]
final_output_file= sys.argv[2]
input_seed = sys.argv[3] # This will consist of {job_id}_{parallel_id}_{bash'sRANDOM}

MAIN_PATH = f"/gpfs/projects/CSE416/Braves/team_data/{state_name}"

PATH_D = f"{MAIN_PATH}/data"
PATH_G = f"{MAIN_PATH}/graphs"
state_data_df = pd.read_csv(f"{PATH_D}/combined_data.csv")
num_districts = len(state_data_df['district'].unique())
# Making the chain
RACES = [Race.BLACK.value, Race.WHITE.value, Race.HISPANIC.value, Race.ASIAN.value]
POP_THRESHOLD = None
if any(state_data_df[race].sum() > 400000 for race in RACES if race.lower() != Race.WHITE.value):
    POP_THRESHOLD = 400000
else:
    POP_THRESHOLD = 200000
PROPOSAL_NODES_REPEAT = 100
SIG_MINORITY_GROUPS = [race for race in RACES if (sum(state_data_df[race])> POP_THRESHOLD and race.lower() != Race.WHITE.value) ]
NUM_DISTRICTS= len(state_data_df['district'].unique())
PROPOSAL_POP_DEV = .03
SPLIT_ALLOW_PAIR_RESELECT = True
NUMBER_OF_THREADS = os.cpu_count() - 1 # defaults to 0 if not parallel, will not be used if not parallel
VRA_ENABLED = True
PARALLEL_ENABLED = False
ANALYZE_ELECTIONS = True
ANALYZE_SIG_MIN_GROUPS = True
ANALYZE_WHITE_POP = True #include_white_pop
ANALYZE_EFFECTIVENESS = True

# During the chain
RECENCY_ELECTION_SCORE = 1 # I am open to changing this, as it's set default for all the scores
CANDIDATE_IN_GROUP_CALIBRATION = .5 # The penalty for the preferred candidate not being in_group, always 1 when they are

CHAIN_MARGIN_NEAR_FINISHED = .9
# If doing parallel, user should be aware of # of threads expected to spawn
# and steps, should be divisible or else some of the final data will
# likely be cancelled by main
CHAIN_TOTAL_STEPS = 40 * NUMBER_OF_THREADS
CHAIN_STORE_DISTR_PLAN = False
EFFECTIVENESS_SCORE_THRESHOLD = .6
MINORITY_EFF_THRESHOLD_DISTRICTS = {} # {race: enacted_eff_districts} THIS NEEDS TO BE IMPORTED EARLY
ITERATIONS_TO_STORE = 30

ei_conf_df = pd.read_csv(f"{PATH_D}/ei_statewide.csv")
IN_GROUP_ALL_RACE = {
        Race.WHITE.value: CANDIDATE_IN_GROUP_CALIBRATION,
        Race.BLACK.value: 1,
        Race.HISPANIC.value: CANDIDATE_IN_GROUP_CALIBRATION,
        Race.ASIAN.value: 1
    }
EI_CONF_ALL_RACE = dict(zip(ei_conf_df['racial_group'], ei_conf_df['confidence']))
state_level_details_json = None
EFF_LOGIT_A = 9
EFF_LOGIT_B = EFF_LOGIT_A / -2

with open(f'{PATH_D}/state_details.json') as f:
  state_level_details_json = json.load(f)


MINORITY_EFF_THRESHOLD_DISTRICTS = state_level_details_json['effective_district_count']
# Enforce at least 1 effective district for VRA
for eff_distr_race, eff_distr_count in MINORITY_EFF_THRESHOLD_DISTRICTS.items():
  if eff_distr_count == 0:
    MINORITY_EFF_THRESHOLD_DISTRICTS[eff_distr_race] = 1



def convert_string_to_seed(string):
  limit = 10**8
  seed_int = int(hashlib.sha256(string.encode('utf-8')).hexdigest(), 16) % limit
  return seed_int



seed_int = convert_string_to_seed(input_seed)
random.seed(seed_int)


elections = [
    Election("PRES24", {"Democratic": "democratic_votes", "Republican": "republican_votes"}),
]

# Election updater helper functions
def prob_conf_conversion(distr_score):
  calibrated_score = 1/(1+np.exp(-(EFF_LOGIT_A * distr_score + EFF_LOGIT_B)))
  return calibrated_score

def collect_default_group_control(district_id, partition,race):
    district_dict = {}
    district_dict[f'{race}_pop'] = partition[race][district_id]
    district_dict['total_pop'] = partition["population"][district_id]
    return district_dict
def evaluate_default_group_control(district_dict, race):
  if(district_dict['total_pop'] == 0):
    return 0
  group_control = min(1,district_dict[f'{race}_pop']/district_dict['total_pop'] * 2)
  return group_control
def calculate_effectiveness_score(partition,race,group_control_collect_function,
                                  group_control_evaluate_function):
  district_eff_scores= {}


  in_group_score = IN_GROUP_ALL_RACE[race]
  ei_conf = EI_CONF_ALL_RACE[race]
  recency = RECENCY_ELECTION_SCORE
  for district in (range(NUM_DISTRICTS)):
    district = district +1

    district_dict = group_control_collect_function(district,partition,race)
    district_score = recency * ei_conf * in_group_score
    group_control = group_control_evaluate_function(district_dict, race)
    district_score *= group_control
    district_calibrated_score = prob_conf_conversion(district_score)
    district_eff_scores[district] = district_calibrated_score


  return district_eff_scores

def calculate_default_eff_score(partition,race):
  return calculate_effectiveness_score(partition,race,
                 collect_default_group_control,
                 evaluate_default_group_control)

def calculate_effective_district_bool(partition,race):
  return {
        district: partition[f"{race}_eff_score"][district] > EFFECTIVENESS_SCORE_THRESHOLD
        for district in partition.parts
    }


def make_updaters(election=True, minority_sig_groups = None, include_white_pop = None, min_eff =None):
  sig_groups = [*minority_sig_groups, Race.WHITE.value] if include_white_pop else minority_sig_groups
  sig_updater = {f"{minority}":updaters.Tally(f"{minority}", alias=f"{minority}", dtype= int)  for minority in sig_groups}
  my_updaters = {"population": updaters.Tally("total", alias="population")}
  my_updaters.update(sig_updater)

  if(election):
    election_updaters = {election.name: election for election in elections}
    my_updaters.update(election_updaters)

  if(min_eff):
    eff_score = {f'{sig_race}_eff_score': partial(calculate_default_eff_score, race=sig_race) for sig_race in sig_groups}
    eff_bool = {f'{sig_race}_eff_bool': partial(calculate_effective_district_bool, race=sig_race) for sig_race in sig_groups}
    my_updaters.update(eff_score)
    my_updaters.update(eff_bool)
  return my_updaters


def make_graph():
  graph = Graph.from_json(f'{PATH_G}/clean_graph.json')
  return graph


def make_initial_partition(graph,precinct_to_districts_df, my_updaters):
  initial_partition = GeographicPartition(
      graph,
      assignment= dict(zip(precinct_to_districts_df['precinct_id'], precinct_to_districts_df['district'])), # Dictionary of precinct to district
      updaters=my_updaters,
  )
  return initial_partition



def make_split_method(max_a = 1000, allow_p_r = True):

  # Split method created, just using gerrychain bipartition for now...
  custom_split_method = partial(
      bipartition_tree,
  )
  return custom_split_method

def make_proposal(ideal_population,pop_col, pop_dev,nodes_rep, custom_split_method = bipartition_tree):
  proposal = partial(
      recom,
      pop_col=pop_col, #Name of the population column within the partition?
      pop_target=ideal_population, # duh
      epsilon= pop_dev, # .02; The epsilon value for population deviation as a percentage of the target population
      node_repeats=nodes_rep, # The number of times to repeat the bipartitioning step. Default is 1.
      method= custom_split_method # Data was stalling on the same pair of districts to figure out, may try and keep...
      # Allows "region" aware areas specified by data (can enforce compactness)
      # method for splitting the combined districts, default is bipartition_tree(), can influence max attempts
  )
  return proposal



def enforce_vra_inclusion(partition):

    # Ignore the initial step as we may enforce > effective districts
    # than in the current plan
    if partition.parent is None:
        return True
    minority_eff_districts = {}
    for minority in SIG_MINORITY_GROUPS:
      minority_eff_districts[minority] = 0
      for district in partition.parts:
         if partition[f'{minority}_eff_bool'][district]:
            minority_eff_districts[minority] += 1

      if(minority_eff_districts[minority] < MINORITY_EFF_THRESHOLD_DISTRICTS[minority]):
        return False
    return True

def make_constraints(i_part, pop_dev,pop_key, ideal_population,VRA = False):

  vra_constraints = [enforce_vra_inclusion]
  base_constraints = [contiguous, constraints.within_percent_of_ideal_population(initial_partition=i_part,percent=pop_dev,pop_key='population')]
  my_constraints = [*base_constraints] if not VRA else [*base_constraints, *vra_constraints]
  return my_constraints

def make_chain(proposal,my_constraints,accept,initial_partition, steps):
  chain = MarkovChain(
      proposal=proposal,
      constraints=my_constraints,
      accept=accept,
      initial_state=initial_partition,
      total_steps=steps
  )
  return chain




def make_data_for_chain():
  my_updaters = make_updaters(election=ANALYZE_ELECTIONS,minority_sig_groups=SIG_MINORITY_GROUPS, include_white_pop=ANALYZE_WHITE_POP, min_eff=  ANALYZE_EFFECTIVENESS)

  graph = make_graph()
  initial_partition = make_initial_partition(graph,state_data_df,my_updaters)
  pop_values = initial_partition["population"].values()
  max_pop = max(pop_values)
  min_pop = min(pop_values)
  ideal_population = sum(initial_partition["population"].values()) / len(initial_partition)
  max_pop_percentage = ideal_population / max_pop
  min_pop_percentage = ideal_population / min_pop
  population_deviation = PROPOSAL_POP_DEV
  BUFFER_FOR_DEV = .00002
  if(min_pop_percentage > population_deviation):
    population_deviation = min_pop_percentage + BUFFER_FOR_DEV
  if(max_pop_percentage > population_deviation):
    population_deviation = max_pop_percentage + BUFFER_FOR_DEV

  custom_split_method = make_split_method(allow_p_r = SPLIT_ALLOW_PAIR_RESELECT)
  proposal = make_proposal(ideal_population=ideal_population, pop_col='total',
                pop_dev=population_deviation,nodes_rep=PROPOSAL_NODES_REPEAT,custom_split_method=custom_split_method)
  my_constraints = make_constraints(initial_partition,pop_dev=population_deviation,
                                    pop_key='population', ideal_population=ideal_population,
                                    VRA = VRA_ENABLED)
  return initial_partition, my_updaters, proposal, my_constraints
def make_chain_from_data(total_steps):
  initial_partition, my_updaters, proposal, my_constraints = make_data_for_chain()
  chain = make_chain(proposal,my_constraints,accept.always_accept,initial_partition,total_steps)
  return chain

def run_chain(out_file,iterations_to_store,chain, store_map = None, parallel_step_tracker=None):
  # This is the # of districts that had a democratic officer in district plan, indexed by run. can infer republican seats by total-dem_seats[i]
  dem_votes = []
  rep_votes = []

  running_district_flips = {}
  data_o =[]
  near_finished_parallel_runs = False
  for i, partition in enumerate(chain):

      if(store_map):
        # Store the current district plan in a light manner
        if (i != 0):
          running_district_flips.update(partition.flips)  # Store the most recent changes of precinct_got_moved: new_distr
          if((i % iterations_to_store) == (iterations_to_store-1) or i == CHAIN_TOTAL_STEPS -1):
            with open(out_file, "a") as f:
                json.dump(running_district_flips,f)
                f.write(',')
                running_district_flips.clear() # Reset to use in further runs
        continue

      dem_row = [partition["PRES24"].totals_for_party["Democratic"][district] for district in range(1, NUM_DISTRICTS + 1)]
      rep_row = [partition["PRES24"].totals_for_party["Republican"][district] for district in range(1, NUM_DISTRICTS + 1)]



      # Account for both minority_sig_groups, white; use total to get fraction
      pop_step = {}
      fpop_step = {} # {race: pop for race in all_sig_races, total: pop}
      for minority in SIG_MINORITY_GROUPS:
        # asc_order_minority_pop = sorted((partition[f"{minority}"].values()))
        asc_order_minority_pop = sorted([(min_pop, distr) for distr, min_pop in partition[f"{minority}"].items()])
        pop_step[minority] = asc_order_minority_pop
      pop_step[Race.WHITE.value] = sorted([(white_pop, distr) for distr, white_pop in partition[Race.WHITE.value].items()])
      pop_step['total'] = partition['population']

      eff_step = {} # {race: pop for race in minority_sig_races}
      for minority in SIG_MINORITY_GROUPS:
           eff_step[minority]= partition[f'{minority}_eff_score']
      eff_step[Race.WHITE.value] = partition[f'{Race.WHITE.value}_eff_score']


      # "Districts": {district: list(nodes) for district, nodes in partition.parts.items()
      # Steps are implict in the "array" order stored
      data_o.append({"Votes": {"D_Votes" : dem_row, "R_Votes": rep_row},
                    "Significant Racial Groups": pop_step, "eff_scores": eff_step})
      # Write out iterate data

      if((i % iterations_to_store) == (iterations_to_store-1) or i == CHAIN_TOTAL_STEPS -1 or near_finished_parallel_runs): # Oh god do not store the first iteration
        with open(out_file, "a") as f: # Using with should auto close it safely in the case of an error
            for step in data_o:
              json.dump(step,f)
              f.write(',')
        data_o = []
      if(parallel_step_tracker):
        fin_runs = ray.get(parallel_step_tracker.increment.remote())

        # Make data repeat every iteration whenever almost done
        if(fin_runs >= CHAIN_TOTAL_STEPS * CHAIN_MARGIN_NEAR_FINISHED):
          near_finished_parallel_runs = True
def before_chain(out_file):
  # Start the array input
  with open(out_file, "w") as f: # Using with should auto close it safely in the case of an error
    f.write('[')
def after_chain(out_file, chain_ids = None):


  # We have a ',' in the outputs, clean by removing
  def remove_last_char(out_file):
    with open(out_file, 'rb+') as f:
      f.seek(0, os.SEEK_END)
      # Verify not empty
      pos = f.tell()
      if pos > 0:
          # Remove the last comma
          f.seek(pos - 1)
          f.truncate()
  # Make a complete json file
  def add_last_array_char(out_file):
    with open(out_file, "a") as f:
      f.write(']')
  def clean_runs_output(out_file):
    remove_last_char(out_file)
    add_last_array_char(out_file)

  # Remove the last ","
  if (chain_ids == None):
    clean_runs_output(out_file=out_file)
  else:
    for end_suffix in chain_ids:
      o_file = f"{out_file}_{end_suffix}.jsonl"
      clean_runs_output(out_file=o_file)

def run_complete_chain(o_file,chain):
  before_chain(out_file= o_file)
  run_chain(o_file,ITERATIONS_TO_STORE, chain, store_map=CHAIN_STORE_DISTR_PLAN)
  after_chain(o_file)
def parallel_run_complete_chain(o_file):
  before_chain(out_file= o_file)
  parallel_main(prefix_out_file= o_file)
  after_chain(o_file)

def parallel_chain_init(num_c):
    ray.init(num_cpus=num_c,runtime_env={"pip": ["gerrychain", "networkx"]})

@ray.remote
class ProgressTracker:
  def __init__(self, threshold):
    self.count = 0
    self.threshold = threshold
  def increment(self):
    self.count += 1
    return self.count
  # # These are likely not needed but can be used to verify
  # def get_count(self):
  #   return self.count
  # def is_finished(self):
  #   return self.count >= self.threshold

# Chain_ident = order it was created under in main
@ray.remote
def parallel_worker(steps, chain_ident,step_tracker, prefix_out_file):
  chain = make_chain_from_data(steps)
  o_file = f"{prefix_out_file}_{chain_ident}.jsonl" # O_file should be unique
  seed_int = convert_string_to_seed(o_file)
  random.seed(seed_int)
  np.random.seed(seed_int)
  run_chain(o_file,ITERATIONS_TO_STORE,chain,CHAIN_STORE_DISTR_PLAN, parallel_step_tracker= step_tracker)
  return chain_ident

def parallel_main(steps, prefix_out_file,number_of_threads):
  tracker = ProgressTracker.remote(steps)
  steps_per_worker = -(steps // -number_of_threads) # Weird ceiling division method in python, shouldn't be an issue on Seawulf
  pending_refs = [parallel_worker.remote(steps_per_worker, i,
                                         tracker,prefix_out_file)
                                         for i in range(number_of_threads)]
  threads_completed= 0
  try:
      while threads_completed < number_of_threads:
          # Wait for any 1 task to finish
          ready_refs, pending_refs = ray.wait(pending_refs, num_returns=1)

          # Get but don't actually store, the return values aren't useful in this case
          # mainly the fact that it finished is useful (apparently synch issues in class method)
          ray.get(ready_refs[0])
          threads_completed += 1
  finally:
      # print(f"Threshold reached. Canceling {len(pending_refs)} remaining tasks.")
      for ref in pending_refs:
          ray.cancel(ref, force=True)
  return range(number_of_threads)
def parallel_run_complete_chain(steps, o_file, number_of_threads):
  for i in range(number_of_threads):
    outp_file = f"{o_file}_{i}.jsonl"
    before_chain(out_file=outp_file)

  parallel_chain_init(number_of_threads)
  chain_identifiers = parallel_main(steps, prefix_out_file= o_file, number_of_threads=number_of_threads)
  after_chain(o_file, chain_identifiers)


if(PARALLEL_ENABLED):
  parallel_run_complete_chain(CHAIN_TOTAL_STEPS,  f"{final_output_file}", number_of_threads=NUMBER_OF_THREADS)
else:
  chain = make_chain_from_data(CHAIN_TOTAL_STEPS)
  run_complete_chain(f"{final_output_file}", chain)




